version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2
    

jobs:
  test-api:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run tests and collect coverage
          command: coverage run test_HelloWorld.py
      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t 8ae53bed-b9ea-4002-bc39-1ee6d8d9a91c





workflows:
  version: 2.
  build-test:
    jobs:
      - test-api
