version: 2.1
orbs:
  python: circleci/python@2.0.3
  codecov: codecov/codecov@3.2.4

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - run: coverage run test_HelloWorld.py 
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
            

workflows:
  test_my_app:
    jobs:
      - build_and_test

